import { UserContext, ExtractedEntities } from "./ai.types.js";

export const reportGeneratorService = {
  generateClientReport(entities: ExtractedEntities, user: UserContext) {
    const clientName = entities.clientName || "Selected Client";
    const month = entities.month || "Current Month (August 2026)";

    return {
      title: `Client Deliverable Report: ${clientName}`,
      markdown: `### Monthly Performance & Deliverable Report: **${clientName}**
**Period:** ${month} | **Prepared for:** ${user.name} (${user.role})

---

#### 1. Executive Summary
This report generator no longer uses placeholder client metrics. Ask Tale Buddy for the active client status so it can answer from live WorkTrack and client records.

---

#### 2. SEO & Organic Visibility
* **Keyword Rankings:** No live SEO ranking source is connected to this local report helper.
* **Organic Traffic Growth:** No live analytics source is connected to this local report helper.

---

#### 3. Social Media & Content Production
* **Visual Posters:** Use live client and WorkTrack records.
* **Video Production:** Use live client and WorkTrack records.

---

#### 4. Paid Ads & Lead Acquisition (Meta & Google PPC)
* **Paid Ads Metrics:** No live ads source is connected to this local report helper.

---

#### 5. Work Tracking & Deliverables Status

| Deliverable Track | Monthly Quota | Completed | Pending Review | On-Time SLA |
| :--- | :--- | :--- | :--- | :--- |
| **Graphic Posters** | Live records required | Live records required | Live records required | Live records required |
| **Video Reels** | Live records required | Live records required | Live records required | Live records required |
| **SEO Focus Sheets** | Live source not connected | Live source not connected | Live source not connected | Live source not connected |
| **Paid Ad Creatives** | Live source not connected | Live source not connected | Live source not connected | Live source not connected |

---

#### 6. Key Recommendations & Next Steps
1. **Use Live Status:** Ask "Show active clients" or "Show delayed client work" for current local database output.
2. **Connect Missing Sources:** Connect SEO, ads, and social analytics before generating performance claims.`
    };
  },

  generatePerformanceReport(entities: ExtractedEntities, user: UserContext) {
    const empName = entities.employeeName || user.name || "Employee";

    return {
      title: `Employee Performance & Productivity Scorecard: ${empName}`,
      markdown: `### Employee Performance Scorecard: **${empName}**
**Review Period:** Current Month | **Evaluation:** Senior Leadership

---

#### 1. Performance Overview
This report helper no longer uses placeholder performance metrics. Use live attendance, WorkTrack, ratings, and points records before making performance claims.

---

#### 2. Key Performance Indicators (KPIs)

| Metric | Target | Actual Score | Performance Tier |
| :--- | :--- | :--- | :--- |
| **Task Completion Rate** | Live records required | Live records required | Live records required |
| **On-Time Submissions** | Live records required | Live records required | Live records required |
| **Rework / Revision Rate** | Live records required | Live records required | Live records required |
| **Attendance & Punctuality** | Live records required | Live records required | Live records required |
| **Work Track Points** | Live records required | Live records required | Live records required |

---

#### 3. Strengths & Contributions
* Live employee strengths require connected performance records.

---

#### 4. Growth Recommendations
* Review live records before assigning recommendations.`
    };
  },

  generateProductivityReport(user: UserContext) {
    return {
      title: `Company-Wide Operations & Productivity Report`,
      markdown: `### Second Tales Operations & Productivity Report
**Generated By:** STEMS AI Intelligence Engine | **Period:** Current Month

---

#### 1. Operations Overview
This report helper no longer uses placeholder company productivity metrics. Use Tale Buddy's live company overview for local database counts.

---

#### 2. Departmental Workload & Output Matrix

| Department | Active Staff | Completed Tasks | Pending Tasks | On-Time SLA |
| :--- | :--- | :--- | :--- | :--- |
| **Graphic Design** | Live records required | Live records required | Live records required | Live records required |
| **Video Production** | Live records required | Live records required | Live records required | Live records required |
| **SEO & Strategy** | Live records required | Live records required | Live records required | Live records required |
| **Growth & Ads** | Live records required | Live records required | Live records required | Live records required |
| **Data Entry** | Live records required | Live records required | Live records required | Live records required |

---

#### 3. Strategic AI Recommendations
1. **Workload Balancing:** Use live WorkTrack workload before reassignment.
2. **Client Review Reminders:** Use live pending client deliverables before sending reminders.`
    };
  }
};
