import { confirmedJobSheets } from './job-evidence.js';
import { z } from 'zod';
import { buildPerformanceReport } from './performance.js';
export const timezone = 'Asia/Kolkata';
export const localDate = value => new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(value));
const shift = (day, n) => new Date(Date.parse(day + 'T12:00:00Z') + n * 86400000).toISOString().slice(0, 10);
const monthEnd = day => new Date(Date.UTC(+day.slice(0,4), +day.slice(5,7), 0)).toISOString().slice(0,10);
export function resolvePeriod({ date_from, date_to, period = 'today' } = {}, now = new Date()) {
  const today = localDate(now); let from, to;
  if (date_from || date_to) { if (!date_from || !date_to) throw new Error('Provide both date_from and date_to.'); from = date_from; to = date_to; }
  else {
    const p = period.toLowerCase().trim(); const weekday = new Date(today+'T12:00Z').getUTCDay(); const monday = shift(today, -((weekday+6)%7));
    if (p === 'today') from = to = today;
    else if (p === 'yesterday') from = to = shift(today,-1);
    else if (p === 'this week') {from=monday;to=today;}
    else if (p === 'last week') {from=shift(monday,-7);to=shift(monday,-1);}
    else if (p === 'this month') {from=today.slice(0,7)+'-01';to=today;}
    else if (p === 'last month') {to=shift(today.slice(0,7)+'-01',-1);from=to.slice(0,7)+'-01';}
    else if (/^last (7|30) days$/.test(p)) {from=shift(today,1-Number(p.split(' ')[1]));to=today;}
    else if (/^\d{4}-\d{2}-\d{2}$/.test(p)) from=to=p;
    else if (/^(monday|tuesday|wednesday|thursday|friday|saturday|sunday)$/.test(p)) { const day=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'].indexOf(p);from=to=shift(today,-((weekday-day+7)%7)); }
    else throw new Error('Use an explicit date range or today, yesterday, this/last week/month, last 7/30 days, or a weekday.');
  }
  for (const day of [from,to]) if (!/^\d{4}-\d{2}-\d{2}$/.test(day) || !Number.isFinite(Date.parse(day+'T12:00Z')) || shift(day,0)!==day) throw new Error('Invalid calendar date.');
  if (from>to || Date.parse(to)-Date.parse(from)>366*86400000) throw new Error('Date range must be ordered and no longer than 367 days. Request older history in separate ranges.');
  return {date_from:from,date_to:to,timezone};
}
const name = e => [e.firstName,e.middleName,e.lastName].filter(Boolean).join(' ');
const normalize = s => String(s||'').toLowerCase().trim().replace(/\s+/g,' ');
export function findEmployees(employees, query) { const q=normalize(query); const exact=employees.filter(e=>[e.id,e.employeeCode,name(e)].some(v=>normalize(v)===q)); return exact.length?exact:employees.filter(e=>normalize(name(e)).includes(q)); }
const profile = e => ({ employee_id:e.id,employee_code:e.employeeCode,name:name(e),company_id:e.companyId,department:e.department?.name||null,designation:e.designation?.title||null,manager_id:e.reportingManagerId||e.managerId||null,status:e.status });
export function matchesDepartment(employee, requested) {
  const q=normalize(requested).replace(/[_-]/g,' ');const department=normalize(employee.department);const title=normalize(employee.designation);
  if(department===q)return true;
  const aliases={'designer':'designer','designers':'designer','design':'designer','graphic designer':'designer','video editor':'video-editor','video editors':'video-editor','video':'video-editor','seo':'seo','development':'development','developer':'development','developers':'development','data entry':'data-entry','performance marketing':'performance-marketing'};
  const track=aliases[q];if(!track)return false;
  if(employee.work_tracks?.includes(track))return true;
  const video=/video|motion|animation|cinemat|videograph|colorist/.test(title+' '+department);
  if(track==='video-editor')return video;
  if(track==='designer')return !video&&/design|graphic|illustrat|visual|ui\/ux/.test(title+' '+department);
  if(track==='development')return /develop|software|engineer/.test(title+' '+department);
  if(track==='seo')return /\bseo\b/.test(title+' '+department);
  if(track==='data-entry')return /data.?entry/.test(title+' '+department);
  return /performance.?marketing|media buyer|paid ads/.test(title+' '+department);
}
const rangeSchema = {date_from:z.string().optional(),date_to:z.string().optional(),period:z.string().optional().describe('Local STEMS dates: today, yesterday, this week, last week, this month, last month, last 7 days, last 30 days, weekday, or YYYY-MM-DD. Explicit dates override period.')};
export function registerIntelligence(server, { request, annotations, security }) {
  const json = data => ({content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data});
  const read = async (path,query={}) => { const r=await request(path,true,query); if(r.isError) throw new Error(r.content[0].text);return JSON.parse(r.content[0].text); };
  const register = (tool,description,schema,fn) => server.registerTool(tool,{description,inputSchema:schema,annotations,...security},async args=> {const started=Date.now();try { const result=await fn(args);console.info(JSON.stringify({event:'mcp_execution',tool,duration_ms:Date.now()-started,status:'success'}));return json(result); }catch(error){console.info(JSON.stringify({event:'mcp_execution',tool,duration_ms:Date.now()-started,status:'error',error:error.message}));return {isError:true,content:[{type:'text',text:error.message}]};}});
  register('search_employee','Resolve a name or employee code to employee_id before asking employee questions. Searches only employees visible to your Stems account. Multiple matches require clarification; never select a duplicate name arbitrarily.',{query:z.string().min(1)},async ({query})=>{const matches=findEmployees(await read('/api/employees'),query);return {matches:matches.map(profile),resolution:matches.length===1?'unique':matches.length?'ambiguous':'not_found'};});
  async function collect(args) {
    const period=resolvePeriod(args); const employees=await read('/api/employees'); const chosen=args.employee_id?employees.filter(e=>e.id===args.employee_id):employees;
    if(args.employee_id&&!chosen.length) throw new Error('Employee not visible to this account. Use search_employee first.');
    const quality={}; const safe=async (key,path,query={})=>{try {const value=await read(path,query);quality[key]={status:'available'};return value;}catch(error){quality[key]={status:'unavailable',reason:error.message};return null;}};
    const months=[]; for(let day=period.date_from.slice(0,7)+'-01';day<=period.date_to;day=shift(monthEnd(day),1)) months.push({month:+day.slice(5,7),year:+day.slice(0,4)});
    const [workEvidence,sheets,context,attendanceChunks,leaveRows]=await Promise.all([safe('tasks','/api/mcp/work-evidence',{employeeId:args.employee_id,dateFrom:period.date_from,dateTo:period.date_to}),safe('data_entry','/api/work-track/data-entry-sheets'),safe('account','/api/auth/me/access'),Promise.all(months.map(m=>safe('attendance_'+m.year+'_'+m.month,'/api/attendance/report',m))),safe('leave','/api/wfh')]);
    const cards=Array.isArray(workEvidence?.cards)?workEvidence.cards:await safe('tasks_fallback','/api/work-track/cards');
    const attendance=attendanceChunks.some(x=>x===null)?null:attendanceChunks.flat();
    const result=buildPerformanceReport({employees,attendance,cards,sheets:sheets===null?null:confirmedJobSheets(sheets,employees),workCompanyId:context?.user?.companyId,workEmployeeIds:workEvidence?.permittedEmployeeIds,month:months[0].month,year:months[0].year,employeeId:args.employee_id,dateFrom:period.date_from,dateTo:period.date_to,sourceStatus:quality});
    const inRange=t=>{if(!t)return false;const d=localDate(t);return d>=period.date_from&&d<=period.date_to;};
    const reports=await Promise.all(result.employees.map(async report=> {
      const employee=chosen.find(e=>e.id===report.employee.id);const scoped=employee.companyId===context?.user?.companyId;
      const supplementalQuality={}; const extra=async(key,path)=>{if(!scoped){supplementalQuality[key]={status:'unavailable',reason:'Different company context.'};return null;}try{const value=await read(path,{employeeId:employee.id});supplementalQuality[key]={status:'available'};return value;}catch(error){supplementalQuality[key]={status:'unavailable',reason:error.message};return null;}};
      const [goals,kras]=args.employee_id?await Promise.all([extra('goals','/api/performance/goals'),extra('kras','/api/performance/kras')]):[null,null];
      const tasks=report.work?.tasks||[];const completed=tasks.filter(t=>t.statusHistory.some(h=>['FINISHED','APPROVED'].includes(h.status)&&inRange(h.timestamp)));
      const pending=tasks.filter(t=>!['FINISHED','APPROVED','OUT_TO_DELIVER'].includes(t.status));const overdue=pending.filter(t=>t.deadline&&localDate(t.deadline)<=period.date_to);
      const commentEvents=(cards||[]).flatMap(c=>(c.comments||[]).filter(x=>x.user?.employee?.id===employee.id&&inRange(x.createdAt)).map(x=>({at:x.createdAt,type:'task_comment',task_id:c.id})));
      const events=commentEvents.concat(tasks.flatMap(t=>t.statusHistory.filter(h=>inRange(h.timestamp)).map(h=>({at:h.timestamp,type:'task_status',task_id:t.id,status:h.status}))).concat((report.dataEntry.rows||[]).map(r=>({at:r.activityType==='edited'?r.editedAt:r.uploadedAt||r.createdAt,date:r.activityDate,type:'data_entry',source_url:r.sourceUrl||null})))).sort((a,b)=>String(a.at||a.date).localeCompare(String(b.at||b.date)));
      return {...report,dataEntry:{...report.dataEntry,rows:report.dataEntry.rows?.slice(0,200),undatedRows:report.dataEntry.undatedRows?.slice(0,50),details_limit:200},employee:{...profile(employee),work_tracks:(workEvidence?.tracks||[]).filter(t=>t.employees.includes(employee.id)).map(t=>t.track)},period,tasks:{available:report.work!==null,assigned:tasks.length,completed_in_period:completed.length,pending_current:pending.length,overdue_as_of_range_end:overdue.length,items:tasks.slice(0,200),details_limit:200},projects:{available:false,reason:'No project entity is exposed by the current WorkCard API. Client association is not a project.'},activity:{events:events.slice(-200),event_count:events.length,first_recorded_activity:events.find(e=>e.at)?.at||null,last_recorded_activity:events.filter(e=>e.at).at(-1)?.at||null},work_sessions:{available:false,active_minutes:null,idle_minutes:null,break_minutes:null,reason:'No measured work-session source exists in the audited schema; task status and attendance are separate evidence.'},leave:{available:Array.isArray(leaveRows),items:Array.isArray(leaveRows)?leaveRows.filter(r=>r.employeeId===employee.id&&localDate(r.startDate)<=period.date_to&&localDate(r.endDate)>=period.date_from).map(r=>({id:r.id,start_date:r.startDate,end_date:r.endDate,status:r.status})):null},performance:{points_scope:'lifetime points on selected work cards; not a period score',points:tasks.reduce((s,t)=>s+(Number(t.pointsEarned)||0),0),score:null,goals,kras},productivity:{completed_tasks:completed.length,data_entry_rows:report.dataEntry.available?report.dataEntry.monthlyRowCount:null,score:null},data_quality:{...quality,...supplementalQuality},historical_trend:report.dataEntry.dailyActivity||[]};
    }));
    return {period,department_directory:[...new Set(reports.map(e=>e.employee.department).filter(Boolean))],work_track_directory:workEvidence?.tracks||[],employees:reports,data_quality:quality,limitations:result.limitations,unattributed_data_entry_rows:result.unattributedDataEntryRows,unattributed_data_entry_scope:result.unattributedDataEntryScope};
  }
  const employeeSchema={employee_id:z.string().min(1).describe('ID returned by search_employee; names are not IDs.'),...rangeSchema};
  register('get_employee_360','Combine employee profile, attendance punches, tasks and status activity, attributed data-entry counts, goals and KRAs for an employee and local date range. Use for overall performance and work questions. Missing measured active/idle/break sessions or project sources are explicit; never interpret missing sources as zero work.',employeeSchema,collect);
  const sections={get_employee_leave:'leave',get_employee_profile:'employee',get_employee_attendance:'attendance',get_employee_tasks:'tasks',get_employee_activity:'activity',get_employee_timeline:'activity',get_employee_work_sessions:'work_sessions',get_employee_projects:'projects',get_employee_performance:'performance',get_employee_productivity:'productivity',get_employee_work_history:'activity'};
  for(const [tool,section]of Object.entries(sections))register(tool,`Retrieve ${section.replaceAll('_',' ')} for employee_id and a STEMS local date range. Resolve names using search_employee. Reports distinguish unavailable data from zero; activity timestamps are not measured work duration.`,employeeSchema,async args=>{const r=await collect(args);const e=r.employees[0];return {employee:e.employee,period:r.period,[section]:e[section],data_quality:e.data_quality};});
  register('get_company_work_summary','Aggregate all employees visible to this account for a date range, including attendance, task workload and data-entry output. Results cover permitted employees only; missing sources remain unavailable.',rangeSchema,async args=>{const r=await collect(args);return {...r,summary:{employees:r.employees.length,recorded_attendance_minutes:r.employees.filter(e=>e.attendance).reduce((s,e)=>s+e.attendance.workMinutes,0),attendance_complete:r.employees.every(e=>e.attendance!==null)}};});
  register('get_department_summary','Resolve a department name, designation or work track (designer, video-editor, SEO, development, data-entry) and summarize permitted employees, with individual attendance, task and data-entry evidence for a local date range. Does not invent a department score.',{department:z.string().min(1),...rangeSchema},async args=>{const r=await collect(args);return {...r,employees:r.employees.filter(e=>matchesDepartment(e.employee,args.department))};});
  register('compare_employees','Compare two or more visible employee IDs using the same date range and recorded metrics. No invented overall performance ranking.',{employee_ids:z.array(z.string()).min(2).max(10),...rangeSchema},async args=>{const r=await collect(args);return {...r,employees:r.employees.filter(e=>args.employee_ids.includes(e.employee.employee_id))};});
  register('get_team_workload','List current pending and overdue tasks per permitted employee, including old unfinished tasks, for a date range. Current status is not historical status.',rangeSchema,collect);
  register('get_overdue_tasks','List overdue unfinished tasks visible to this account; requires a date range. Deadlines are compared to the local range end and statuses are current.',rangeSchema,async args=>{const r=await collect(args);return {...r,employees:r.employees.map(e=>({employee:e.employee,tasks:e.tasks.items.filter(t=>!['FINISHED','APPROVED','OUT_TO_DELIVER'].includes(t.status)&&t.deadline&&localDate(t.deadline)<=r.period.date_to)}))};});
  for (const tool of ['get_currently_working_employees', 'get_inactive_employees']) register(tool, 'Check whether measured live working/inactive status is available. Current schema has no live work-session telemetry; attendance punches and publication timestamps must not be called current working/idle status.', rangeSchema, async args => ({period:resolvePeriod(args),available:false,employees:null,reason:'Measured live work-session telemetry is not available in STEMS.'}));
  const metrics={data_entry_rows:e=>e.productivity.data_entry_rows,completed_tasks:e=>e.tasks.available?e.tasks.completed_in_period:null,attendance_minutes:e=>e.attendance?.workMinutes??null,pending_tasks:e=>e.tasks.available?e.tasks.pending_current:null,overdue_tasks:e=>e.tasks.available?e.tasks.overdue_as_of_range_end:null};
  for(const tool of ['get_top_performers','get_low_performers'])register(tool,'Rank visible employees by a specified recorded metric for a date range. This is a metric ranking, not an overall employment/performance judgment. Unavailable measurements are excluded and ties retained.',{metric:z.enum(['data_entry_rows','completed_tasks','attendance_minutes','pending_tasks','overdue_tasks']),...rangeSchema},async args=>{const r=await collect(args);const measured=r.employees.map(e=>({employee:e.employee,value:metrics[args.metric](e)}));return {period:r.period,metric:args.metric,ranking:measured.filter(e=>e.value!==null).sort((a,b)=>tool==='get_top_performers'?b.value-a.value:a.value-b.value),unavailable:measured.filter(e=>e.value===null).map(e=>e.employee),data_quality:r.data_quality};});
  register('compare_departments','Compare department totals for the same local date range using permitted employees and recorded task/data-entry metrics. Missing data is reported separately, and department totals are not performance scores.',{departments:z.array(z.string()).min(2).max(10),...rangeSchema},async args=>{const r=await collect(args);return {period:r.period,departments:args.departments.map(department=>({department,employees:r.employees.filter(e=>matchesDepartment(e.employee,department))})),data_quality:r.data_quality};});
  register('get_department_performance','Resolve a department, designation or verified work track and get recorded work evidence and date range; includes employee task, attendance and data-entry metrics without inventing an overall score.',{department:z.string().min(1),...rangeSchema},async args=>{const r=await collect(args);return {...r,employees:r.employees.filter(e=>matchesDepartment(e.employee,args.department))};});
  register('compare_employee_periods','Compare one visible employee across two explicit local date ranges, such as this week versus last week. Uses identical source definitions; no invented trend score.',{employee_id:z.string(),first_from:z.string(),first_to:z.string(),second_from:z.string(),second_to:z.string()},async args=>({first:await collect({employee_id:args.employee_id,date_from:args.first_from,date_to:args.first_to}),second:await collect({employee_id:args.employee_id,date_from:args.second_from,date_to:args.second_to})}));
  register('plan_employee_query','Plan a natural-language employee/company question before execution. Supply conversation context for follow-ups. Returns ordered tools, a local date range and missing context. The client must execute the plan and clarify ambiguous employee matches.',{question:z.string().min(1),employee_id:z.string().optional(),period:z.string().optional(),...rangeSchema},async args=>{const q=args.question.toLowerCase();const period=args.period||['yesterday','last week','this week','last month','this month','last 7 days','last 30 days','today','monday','tuesday','wednesday','thursday','friday','saturday','sunday'].find(p=>q.includes(p))||'today';const dates=q.match(/\d{4}-\d{2}-\d{2}/g);const range=resolvePeriod({...args,period,...(dates?.length===2?{date_from:dates[0],date_to:dates[1]}:{})});const tool=/department/.test(q)?'get_department_summary':/who|company|team|all employees/.test(q)?'get_company_work_summary':'get_employee_360';return {question:args.question,period:range,steps:args.employee_id&&q.includes('compare')&&q.includes('this week')&&q.includes('last week')?[{tool:'compare_employee_periods',arguments:{employee_id:args.employee_id,first_from:resolvePeriod({period:'this week'}).date_from,first_to:resolvePeriod({period:'this week'}).date_to,second_from:resolvePeriod({period:'last week'}).date_from,second_to:resolvePeriod({period:'last week'}).date_to}}]:args.employee_id?[{tool,arguments:{employee_id:args.employee_id,...range}}]:[{tool:'search_employee',requires:'employee name or code from question/context'},{tool,requires:'unique employee_id from lookup or department name'}],context_required:args.employee_id?[]:['Resolve employee or department; preserve prior employee_id for follow-ups.'],unsupported_measurements:/idle|break|currently working|active right now|inactive/.test(q)?['Measured live work sessions are unavailable; do not infer from attendance or last publication.']:[]};});
}
